# Generated by Django 5.1.2 on 2026-08-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '備忘録',
                'verbose_name_plural': '備忘録一覧',
                'db_table': 'memo_notes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('total_quantity', models.IntegerField(default=0)),
                ('marketable_quantity', models.IntegerField(default=0)),
                ('is_production_completed', models.BooleanField(default=False)),
                ('target_platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品一覧',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SalesPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('fee_rate', models.FloatField(default=0.0)),
                ('fee_fixed', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': '販売プラットフォーム',
                'verbose_name_plural': '販売プラットフォーム一覧',
                'db_table': 'sales_platforms',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定一覧',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '倉庫',
                'verbose_name_plural': '倉庫一覧',
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('actual_cost', models.FloatField(default=0.0)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=1.0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('original_amount', models.FloatField(blank=True, null=True)),
                ('actual_qty', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_unit_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_budget', models.BooleanField(default=False)),
                ('finance_record_id', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='app_core.product')),
            ],
            options={
                'verbose_name': '原価項目',
                'verbose_name_plural': '原価項目一覧',
                'db_table': 'cost_items',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('produced_quantity', models.IntegerField(default=0)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_colors/')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app_core.product')),
            ],
            options={
                'verbose_name': '商品カラー',
                'verbose_name_plural': '商品カラー一覧',
                'db_table': 'product_colors',
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.ForeignKey(db_column='color_id', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app_core.productcolor')),
            ],
            options={
                'verbose_name': '商品パーツ',
                'verbose_name_plural': '商品パーツ一覧',
                'db_table': 'product_parts',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('color', models.ForeignKey(db_column='color_id', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app_core.productcolor')),
            ],
            options={
                'verbose_name': '商品価格',
                'verbose_name_plural': '商品価格一覧',
                'db_table': 'product_prices',
            },
        ),
    ]
