# Generated by Django 5.1.2 on 2026-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('initial_quantity', models.IntegerField()),
                ('remaining_qty', models.IntegerField()),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('finance_record_id', models.IntegerField(blank=True, db_column='finance_record_id', null=True)),
            ],
            options={
                'verbose_name': '消耗品',
                'verbose_name_plural': '消耗品一覧',
                'db_table': 'consumable_items',
            },
        ),
        migrations.CreateModel(
            name='ConsumableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('change_qty', models.IntegerField()),
                ('value_cny', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '消耗品ログ',
                'verbose_name_plural': '消耗品ログ一覧',
                'db_table': 'consumable_logs',
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('remaining_qty', models.IntegerField()),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('finance_record_id', models.IntegerField(blank=True, db_column='finance_record_id', null=True)),
            ],
            options={
                'verbose_name': '固定資産',
                'verbose_name_plural': '固定資産一覧',
                'db_table': 'fixed_assets_detail',
            },
        ),
        migrations.CreateModel(
            name='FixedAssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('decrease_qty', models.IntegerField()),
                ('reason', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '固定資産ログ',
                'verbose_name_plural': '固定資産ログ一覧',
                'db_table': 'fixed_asset_logs',
            },
        ),
    ]
