# Generated by Django 5.1.2 on 2026-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('asset_type', models.CharField(default='資産', max_length=100)),
                ('finance_record_id', models.IntegerField(blank=True, db_column='finance_record_id', null=True)),
                ('product_id', models.IntegerField(blank=True, db_column='product_id', null=True)),
            ],
            options={
                'verbose_name': '資産負債項目',
                'verbose_name_plural': '資産負債項目一覧',
                'db_table': 'company_balance_items',
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('account_id', models.IntegerField(blank=True, db_column='account_id', null=True)),
                ('order_id', models.IntegerField(blank=True, db_column='order_id', null=True)),
                ('related_item_id', models.IntegerField(blank=True, null=True)),
                ('related_cost_id', models.IntegerField(blank=True, db_column='related_cost_id', null=True)),
            ],
            options={
                'verbose_name': '財務流水',
                'verbose_name_plural': '財務流水一覧',
                'db_table': 'finance_records',
            },
        ),
    ]
