# Generated by Django 5.1.2 on 2026-08-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'オフラインテンプレート',
                'verbose_name_plural': 'オフラインテンプレート一覧',
                'db_table': 'offline_templates',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=255, unique=True)),
                ('order_type', models.CharField(default='线上', max_length=50)),
                ('final_order_no', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('deposit_amount', models.FloatField(default=0.0)),
                ('final_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(default='待发货', max_length=100)),
                ('total_amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='CNY', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('target_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('discount_note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '販売注文',
                'verbose_name_plural': '販売注文一覧',
                'db_table': 'sales_orders',
            },
        ),
        migrations.CreateModel(
            name='OfflineTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('preset_price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('remaining_quantity', models.IntegerField(default=0)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_sales.offlinetemplate')),
            ],
            options={
                'verbose_name': 'オフラインテンプレート明細',
                'verbose_name_plural': 'オフラインテンプレート明細一覧',
                'db_table': 'offline_template_items',
            },
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.FloatField(default=0.0)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('refund_date', models.DateField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_quantity', models.IntegerField(default=0)),
                ('is_resend', models.BooleanField(default=False)),
                ('resend_quantity', models.IntegerField(default=0)),
                ('cost_item_id', models.IntegerField(blank=True, db_column='cost_item_id', null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='app_sales.salesorder')),
            ],
            options={
                'verbose_name': '返金・返品記録',
                'verbose_name_plural': '返金・返品記録一覧',
                'db_table': 'order_refunds',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_sales.salesorder')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細一覧',
                'db_table': 'sales_order_items',
            },
        ),
    ]
