# Generated by Django 5.1.2 on 2026-08-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinetemplateitem',
            options={'verbose_name': 'オフラインテンプレート明細', 'verbose_name_plural': 'オフラインテンプレート明细一覧'},
        ),
        migrations.CreateModel(
            name='PresaleOrderBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_order_no', models.CharField(db_index=True, max_length=255)),
                ('final_order_no', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('deposit_order', models.ForeignKey(db_column='deposit_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='bound_finals', to='app_sales.salesorder')),
                ('final_order', models.ForeignKey(blank=True, db_column='final_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bound_deposits', to='app_sales.salesorder')),
            ],
            options={
                'verbose_name': '予約注文紐付け',
                'verbose_name_plural': '予約注文紐付け一覧',
                'db_table': 'presale_order_bindings',
            },
        ),
    ]
