# Generated by Django 5.1.2 on 2026-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sales', '0002_alter_offlinetemplateitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='final_order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
