# Generated by Django 5.1.2 on 2026-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('change_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('sale_amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('is_other_out', models.BooleanField(default=False)),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', null=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField(blank=True, db_column='order_id', null=True)),
                ('cost_item_id', models.IntegerField(blank=True, db_column='cost_item_id', null=True)),
            ],
            options={
                'verbose_name': '在庫ログ',
                'verbose_name_plural': '在庫ログ一覧',
                'db_table': 'inventory_logs',
            },
        ),
    ]
